name: Sync custom.css to Training Platform

on:
  push:
    paths:
      - "dark-creative/css/custom.css"
    branches:
      - main

jobs:
  sync-file:
    if: github.actor != 'github-actions[bot]'  # Prevents infinite loops
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Copy custom.css to the target repo
        env:
          PAT_TOKEN: ${{ secrets.SYNC_CSS_GFAI }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clone the target repository (Training-Platform)
          git clone https://$PAT_TOKEN@github.com/Green-Finance-AI/Training-Platform.git target-repo
          
          # Copy the file
          cp dark-creative/css/custom.css target-repo/css/custom.css

          cd target-repo
          git add css/custom.css

          # Commit only if there are changes, otherwise exit successfully
          git diff --cached --exit-code || (git commit -m "Sync custom.css from Green Finance AI repo" && git push)
